name: Dispatch Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 831852
          private-key: ${{ secrets.WORKFLOW_KICKER_PRIVATE_KEY }}
          owner: buty4649
          repositories: homebrew-tap
      - name: Run gh command
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/buty4649/homebrew-tap/dispatches \
            --method POST \
            --field event_type=update --field client_payload='{"ref":"main"}'
