name: Dispatch Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 831852
          private-key: ${{ secrets.WORKFLOW_KICKER_PRIVATE_KEY }}
          owner: buty4649
          repositories: homebrew-tap
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'buty4649',
              repo: 'homebrew-tap',
              workflow_id: 'update.yml',
              ref: 'main'
            })
