name: Ruby on Windows

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: ruby --version
      - run: bundle version
      - run: gcm ruby
      - uses: actions/checkout@v4
      - run: |
          gem install bundler:2.5.11
          bundle install
